services:
  db:
    image: mysql:8.0
    container_name: db_donaciones
    restart: always
    environment:
      MYSQL_DATABASE: biblioteca_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user_donaciones
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/db/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
